# Use root/example as user/password credentials
version: '3.1'

services:
  btax-db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: gabridc
      MARIADB_PASSWORD: 20z3usG0d22
    ports:
      - "3306:3306"
    networks:
      - btax-network
    volumes:
      - ./database/data/:/var/lib/mysql
  yfinance:
    image: yfinance-api
    restart: always
    ports:
      - "5001:5000"
    networks:
      - btax-network
    #volumes:
    #  - ./YFinance_API:/YFinance_API
networks:
  btax-network:
    driver: bridge